### ISSUE TITLE
Can you update the addon version?

### ISSUE THREAD

**Issue by danielpuche** [Redoute/QGIS-sync-map-and-attribute-table#7]
Hello can you update the plugin Sync Composer With Map for 2021 version on qgis?

So i can sync my tables from phpmyadin with geopack. It is possible with this addon?

**Comment by Redoute** [comment]
Sorry, my plugin has nothing to do with file or database syncing. This was experimental only, I don't think anyone uses it any more.

**Comment by danielpuche** [comment]
Ok pfff then do you know any form for sync the geopack with the tables? Because i got sync my phpmyadmin with tables in qgis, but one time create the geopack based in my tables, when i create the points inside or if i modified or update something inside of geopack is not sync with tables mother. If i update any attribute in the table since phpmyadmin or since the table imported from web to qgis is sync  but inside of geopack is not.

Anyway Ty.
